version: '3.6'

services:
  mysql_dev:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=default
      - MYSQL_ROOT_PASSWORD=default
      - MYSQL_DATABASE=astro-ai-db-dev
      - 'TZ=Asia/Shanghai'
  redis_dev:
    image: redis:7
    ports:
      - 6379:6379
    environment:
      - PASSWORD=123456
    volumes:
      - ./redis:/data
volumes:
  db_data:
    driver: local
