@host = http://localhost:4321

GET {{host}}/api/users.json

###

GET {{host}}/api/users/M12.json

###

POST {{host}}/api/users.json

###

PUT {{host}}/api/users/M12.json

###

DELETE {{host}}/api/users/M12.json

###

POST {{host}}/api/users/M12.json
